# -*- coding: utf-8 -*-
"""Riyad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5hV7uezCDen2ReAcxbUE0fadJ-E0WBN

**Setup — Install & Import Libraries**
"""

!pip install prophet --quiet

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta

from prophet import Prophet

plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['axes.grid'] = True

np.random.seed(42)

print("Libraries are installed")

"""**Generating the dataset**"""

start_date = datetime(2023, 1, 1)
end_date   = datetime(2024, 6, 30)
all_dates  = pd.date_range(start=start_date, end=end_date, freq='D')

balance = 500000.0
records = []

project_dates = pd.to_datetime(
    np.sort(np.random.choice(all_dates, size=7, replace=False))
)
dataset_sale_dates = pd.to_datetime(
    np.sort(np.random.choice(all_dates, size=2, replace=False))
)
workshop_dates = pd.to_datetime(
    np.sort(np.random.choice(all_dates, size=5, replace=False))
)

SENIOR_BIWEEKLY = 18000
JUNIOR_BIWEEKLY = 9750

for date in all_dates:
    day_of_month = date.day
    ts = pd.Timestamp(date)

    if day_of_month == 1:
        months_passed = (date.year - start_date.year) * 12 + (date.month - start_date.month)
        licensing = np.random.normal(loc=20000 + months_passed * 1000, scale=1500)
        licensing = max(licensing, 0)
        balance += licensing
        records.append([date, round(licensing, 2), 'In', 'Model Licensing', round(balance, 2)])

    if ts in project_dates:
        revenue = np.random.normal(loc=85000, scale=25000)
        revenue = max(revenue, 30000)
        balance += revenue
        records.append([date, round(revenue, 2), 'In', 'Project Revenue', round(balance, 2)])

    if ts in dataset_sale_dates:
        dataset_income = np.random.normal(loc=60000, scale=15000)
        dataset_income = max(dataset_income, 40000)
        balance += dataset_income
        records.append([date, round(dataset_income, 2), 'In', 'Dataset Sale', round(balance, 2)])

    if ts in workshop_dates:
        workshop = np.random.normal(loc=18000, scale=4000)
        workshop = max(workshop, 8000)
        balance += workshop
        records.append([date, round(workshop, 2), 'In', 'Training Workshop', round(balance, 2)])

    if day_of_month in [1, 15]:
        senior_salary = np.random.normal(loc=SENIOR_BIWEEKLY, scale=400)
        senior_salary = max(senior_salary, 0)
        balance -= senior_salary
        records.append([date, -round(senior_salary, 2), 'Out', 'Senior Engineer Salary', round(balance, 2)])

    if day_of_month in [1, 15]:
        junior_salary = np.random.normal(loc=JUNIOR_BIWEEKLY, scale=300)
        junior_salary = max(junior_salary, 0)
        balance -= junior_salary
        records.append([date, -round(junior_salary, 2), 'Out', 'Junior Engineer Salary', round(balance, 2)])

    if np.random.rand() < 0.30:
        if np.random.rand() < 0.05:
            gpu = np.random.normal(loc=8000, scale=2000)
        else:
            gpu = np.random.normal(loc=900, scale=300)
        gpu = max(gpu, 0)
        balance -= gpu
        records.append([date, -round(gpu, 2), 'Out', 'GPU Rental', round(balance, 2)])

    if day_of_month == 1:
        rent = np.random.normal(loc=6500, scale=150)
        rent = max(rent, 0)
        balance -= rent
        records.append([date, -round(rent, 2), 'Out', 'Co-working Rent', round(balance, 2)])

    if day_of_month == 1:
        months_passed = (date.year - start_date.year) * 12 + (date.month - start_date.month)
        tools = np.random.normal(loc=3500 + months_passed * 80, scale=400)
        tools = max(tools, 0)
        balance -= tools
        records.append([date, -round(tools, 2), 'Out', 'Software & Tools Subscriptions', round(balance, 2)])


df = pd.DataFrame(records, columns=['Date', 'Amount', 'Type', 'Category', 'Balance'])



df = df.sort_values('Date').reset_index(drop=True)

print(f"Synthetic dataset generated.")
print(f"Total rows: {len(df)}")
print(f"Date range: {start_date.date()} untill {end_date.date()}")
print(f"\nSample rows:")
df.head(10)

df.to_excel("synthetic_ai_startup_transactions.xlsx", index=False)

print("Dataset 'synthetic_ai_startup_transactions.xlsx' is saved")

"""**Clean the Data + Compute Daily Net Cash Flow**"""

print("Task 1: Cleaning the data")

df_clean = df.copy()
print(f"\n Raw rows before cleaning : {len(df_clean)}")

df_clean['Date'] = pd.to_datetime(df_clean['Date'], errors='coerce')
before = len(df_clean)
df_clean = df_clean.dropna(subset=['Date'])
print(f"Rows dropped (wrong date)  : {before - len(df_clean)}")

before = len(df_clean)
df_clean = df_clean.drop_duplicates(keep='first')
print(f"Duplicate rows removed: {before - len(df_clean)}")

before = len(df_clean)
df_clean = df_clean.dropna(subset=['Amount'])
print(f"Rows dropped (no amount): {before - len(df_clean)}")

df_clean['Category'] = df_clean['Category'].fillna('Uncategorized')
print(f"Category blanks filled   : (filled with 'Uncategorized')")

df_clean = df_clean.sort_values('Date').reset_index(drop=True)
print(f"\nClean rows after cleaning : {len(df_clean)}")

in_positive  = (df_clean[df_clean['Type'] == 'In']['Amount'] >= 0).all()
out_negative = (df_clean[df_clean['Type'] == 'Out']['Amount'] <= 0).all()
print(f"\n Sign check:")
print(f" All 'In'  amounts positive : {in_positive}  "  if in_positive  else "   Some 'In' amounts are negative!")
print(f" All 'Out' amounts negative : {out_negative} " if out_negative else "    Some 'Out' amounts are positive!")

print("  Task 2: Daily Net Cash Flow")

daily_net = (
    df_clean
    .groupby('Date')['Amount']
    .sum()
    .reset_index()
    .rename(columns={'Amount': 'Net_Cash_Flow'})
)

full_date_range = pd.DataFrame({
    'Date': pd.date_range(start=df_clean['Date'].min(),
                          end=df_clean['Date'].max(),
                          freq='D')
})

daily_net = full_date_range.merge(daily_net, on='Date', how='left')
daily_net['Net_Cash_Flow'] = daily_net['Net_Cash_Flow'].fillna(0)

print(f"\n Date range  : {daily_net['Date'].min().date()} → {daily_net['Date'].max().date()}")
print(f"   Total days  : {len(daily_net)}")
print(f"   Days with positive net flow : {(daily_net['Net_Cash_Flow'] > 0).sum()}")
print(f"   Days with negative net flow : {(daily_net['Net_Cash_Flow'] < 0).sum()}")
print(f"   Days with zero flow         : {(daily_net['Net_Cash_Flow'] == 0).sum()}")
print(f"\n Average daily net flow : {daily_net['Net_Cash_Flow'].mean():,.0f} SAR")
print(f"   Best day               : {daily_net['Net_Cash_Flow'].max():,.0f} SAR")
print(f"   Worst day              : {daily_net['Net_Cash_Flow'].min():,.0f} SAR")

fig, ax = plt.subplots(figsize=(14, 5))
colors = ['#8e7cc3ff' if v >= 0 else '#c36b4eff' for v in daily_net['Net_Cash_Flow']]
ax.bar(daily_net['Date'], daily_net['Net_Cash_Flow'], color=colors, width=1.0, alpha=0.75)
ax.axhline(y=0, color='white', linewidth=0.8, linestyle='--', alpha=0.5)
ax.set_title('Daily Net Cash Flow: AI Startup (Jan 2023 – Jun 2024)', fontsize=14, pad=15)
ax.set_xlabel('Date')
ax.set_ylabel('Net Cash Flow (SAR)')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print(f"\n daily_net is ready — {len(daily_net)} rows, 2 columns (Date + Net_Cash_Flow)")
print("\n Sample rows:")
daily_net.head(10)

FORECAST_MONTHS = 3 #@param {type:"slider", min:1, max:5, step:1}
print(f"  Step 1: Dynamic Data split ({FORECAST_MONTHS} MONTHS)")

forecast_days = FORECAST_MONTHS * 30

prophet_df = daily_net.rename(columns={'Date': 'ds', 'Net_Cash_Flow': 'y'})

split_date = prophet_df['ds'].max() - pd.Timedelta(days=forecast_days)

train_df = prophet_df[prophet_df['ds'] <= split_date]
test_df  = prophet_df[prophet_df['ds'] > split_date]

print(f"   Dynamic split for {FORECAST_MONTHS} Month(s) complete:")
print(f"   Total History Days: {len(prophet_df)} days")
print(f"   Training Set      : {len(train_df)} days ({train_df['ds'].min().date()} → {train_df['ds'].max().date()})")
print(f"   Testing Set       : {len(test_df)} days ({test_df['ds'].min().date()} → {test_df['ds'].max().date()})")


print(f"  \nStep 2: Train and Forecast for the next {forecast_days} Days")

model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False,
    changepoint_prior_scale=0.15,
    seasonality_prior_scale=10
)

print(f" Training Prophet on historical data prior to {split_date.date()}...")
model.fit(train_df)

future = model.make_future_dataframe(periods=forecast_days)
forecast = model.predict(future)

forecast_test_period = forecast[forecast['ds'] > split_date][['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

print(f" Backtest forecast generated for the requested horizon.")


print("  \nStep 3: Evaluate Accuracy for selected Horizon")

evaluation_df = pd.merge(test_df, forecast_test_period, on='ds')
evaluation_df['Absolute_Error'] = (evaluation_df['y'] - evaluation_df['yhat']).abs()
mae = evaluation_df['Absolute_Error'].mean()

print(f" Validation Results for {FORECAST_MONTHS} Month(s):")
print(f"   Mean Absolute Error (MAE): {mae:,.2f} SAR per day")


print("  \n Step 4: Plot the backtest")

fig, ax = plt.subplots(figsize=(16, 6))
colors = ['#8e7cc3ff' if v >= 0 else '#c36b4eff' for v in prophet_df['y']]
ax.bar(prophet_df['ds'], prophet_df['y'], color=colors, width=1.0, alpha=0.25, label='Actual History')
ax.plot(forecast['ds'], forecast['yhat'], color='#f39c12', linewidth=2, label=f'Prophet Backtest ({FORECAST_MONTHS} Mo)')
ax.fill_between(forecast_test_period['ds'], forecast_test_period['yhat_lower'], forecast_test_period['yhat_upper'],
                 color='#f39c12', alpha=0.15, label='Uncertainty Interval')
ax.axvline(x=split_date, color='purple', linewidth=1.5, linestyle='--', label=f'Start of {FORECAST_MONTHS}-Month Test')
ax.set_title(f'Backtest Validation: Forecast vs Known Data ({FORECAST_MONTHS} Months)', fontsize=14, pad=15)
ax.set_xlabel('Date')
ax.set_ylabel('Net Cash Flow (SAR)')
ax.legend(loc='upper left')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("\n NOTE: This cell validates model accuracy against KNOWN historical")
print("   data (backtest). It does NOT forecast the real future — see the")
print("   next cell for the actual forward-looking forecast used in the")
print("   balance, what-if, and insolvency features below.")

print(f"  Train on full history and forecast {FORECAST_MONTHS} Month(s) forward")

future_model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False,
    changepoint_prior_scale=0.15,
    seasonality_prior_scale=10
)

print(f"\n Training on full history ({prophet_df['ds'].min().date()} → {prophet_df['ds'].max().date()})...")
future_model.fit(prophet_df)

future_full = future_model.make_future_dataframe(periods=forecast_days)
forecast_full = future_model.predict(future_full)

future_only = forecast_full[forecast_full['ds'] > prophet_df['ds'].max()][
    ['ds', 'yhat', 'yhat_lower', 'yhat_upper']
]

print(f"  True future forecast generated")
print(f"   Forecast period: {future_only['ds'].min().date()} → {future_only['ds'].max().date()}")
print(f"   Avg predicted daily net flow: {future_only['yhat'].mean():,.0f} SAR/day")

print("  Step 1: Reconstruct Historical Balance")

STARTING_BALANCE = 500000.0

historical_balance = daily_net.copy()
historical_balance['Balance'] = STARTING_BALANCE + historical_balance['Net_Cash_Flow'].cumsum()

current_balance = historical_balance['Balance'].iloc[-1]

print(f"\n Balance anchor set at last known date: {historical_balance['Date'].iloc[-1].date()}")
print(f"   Anchor Balance: {current_balance:,.0f} SAR")


print(f"  \nStep 2: Build running balance for {FORECAST_MONTHS} months ahead")

forecast_balance = future_only.copy()
forecast_balance = forecast_balance.rename(columns={'ds': 'Date'})

forecast_balance['Balance'] = current_balance + forecast_balance['yhat'].cumsum()

daily_margin = (forecast_balance['yhat_upper'] - forecast_balance['yhat_lower']) / 2
cumulative_sd = np.sqrt((daily_margin ** 2).cumsum())

forecast_balance['Balance_Lower'] = forecast_balance['Balance'] - cumulative_sd
forecast_balance['Balance_Upper'] = forecast_balance['Balance'] + cumulative_sd

print(f"\n Future forecasted balance generated for {FORECAST_MONTHS} month(s).")
print(f"   Balance today             : {current_balance:,.0f} SAR")
print(f"   Ending Balance (yhat)     : {forecast_balance['Balance'].iloc[-1]:,.0f} SAR")
print(f"   Best case                : {forecast_balance['Balance_Upper'].iloc[-1]:,.0f} SAR")
print(f"   Worst case               : {forecast_balance['Balance_Lower'].iloc[-1]:,.0f} SAR")

DECISION_DESCRIPTION = "Hire a new engineer"  #@param {type:"string"}
DECISION_TYPE = "Expense"  #@param ["Expense", "Income"]
DECISION_BEHAVIOR = "Recurring" #@param ["Recurring", "One-time"]
DECISION_AMOUNT = 20000  #@param {type:"number"}

SAFE_MINIMUM_BALANCE = 50000  #@param {type:"number"}

print(f"  Step 1: Simulating Decision over {FORECAST_MONTHS} months")

decision_start = forecast_balance['Date'].min()
sign = -1 if DECISION_TYPE == "Expense" else 1

scenario_balance = forecast_balance[['Date', 'Balance']].copy()
scenario_balance = scenario_balance.rename(columns={'Balance': 'Baseline_Balance'})

days_since_start = (scenario_balance['Date'] - decision_start).dt.days

if DECISION_BEHAVIOR == "Recurring":
    months_elapsed = np.where(days_since_start >= 0, (days_since_start // 30) + 1, 0)
    cumulative_effect = sign * months_elapsed * DECISION_AMOUNT
else:
    cumulative_effect = np.where(days_since_start >= 0, sign * DECISION_AMOUNT, 0)

scenario_balance['Scenario_Balance'] = scenario_balance['Baseline_Balance'] + cumulative_effect

print(f" Simulation complete for the selected {FORECAST_MONTHS}-month window.")


print("  \nStep 2: Detecting insolvency risks")

baseline_risk = scenario_balance[scenario_balance['Baseline_Balance'] <= SAFE_MINIMUM_BALANCE]
scenario_risk = scenario_balance[scenario_balance['Scenario_Balance'] <= SAFE_MINIMUM_BALANCE]

if len(baseline_risk) > 0:
    print(f" Baseline warning: Balance is projected to drop below the safe minimum by {baseline_risk['Date'].iloc[0].date()}")

if len(scenario_risk) > 0:
    risk_date = scenario_risk['Date'].iloc[0]
    print(f" Early risk warning triggered by decision: ({DECISION_DESCRIPTION})")
    print(f"   If you proceed with this decision, your balance will drop below the safe minimum by: 【 {risk_date.date()} 】")
    print(f"   (within the next {FORECAST_MONTHS} month(s)).")

    deficit_amount = SAFE_MINIMUM_BALANCE - scenario_risk['Scenario_Balance'].iloc[0]
    print(f"\n Future concept: Projected deficit of {deficit_amount:,.0f} SAR — "
          f"this warning could later be linked to real financing products via an Open Banking API.")
else:
    print(f" Financially safe: You can proceed with this decision ({DECISION_DESCRIPTION}) confidently. Balance will stay above the safe minimum for the entire {FORECAST_MONTHS}-month forecast period.")

print("  \nStep 3: Plot the insolvency comparison")

fig, ax = plt.subplots(figsize=(16, 6))

ax.plot(scenario_balance['Date'], scenario_balance['Baseline_Balance'], color='#8e7cc3ff', linewidth=2.5, label='Baseline (Do Nothing)')
ax.plot(scenario_balance['Date'], scenario_balance['Scenario_Balance'], color='#e74c3c', linewidth=2.5, linestyle='--', label=f'Scenario: {DECISION_DESCRIPTION}')
ax.axhline(y=SAFE_MINIMUM_BALANCE, color='#c36b4eff', linewidth=1.5, linestyle='-.', label=f'Safe Minimum Threshold ({SAFE_MINIMUM_BALANCE:,.0f} SAR)')

if len(scenario_risk) > 0:
    ax.scatter(scenario_risk['Date'], scenario_risk['Scenario_Balance'], color='red', marker='x', s=100, zorder=5, label='Insolvency Risk Days')

ax.set_title(f'What-If Insolvency Risk Analysis — {FORECAST_MONTHS} Month(s)', fontsize=14, pad=15)
ax.set_xlabel('Date')
ax.set_ylabel('Balance (SAR)')
ax.legend(loc='upper left')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()